added GET request by id
timoshevichaleks/app-jsonplaceholder pull request #2
Opened 2021-09-12 21:13 UTC by timoshevichaleks

Added navigation between Posts and Posts Details.
Adedd GET request by id

2021-09-13 10:40 UTC, dgutoryan requested changes

2021-09-13 10:40 UTC, dgutoryan commented on src/app/app.component.html
> +      <h1 class="py-5 text-center">Some Posts</h1>
The same header for posts and post details?

2021-09-13 10:40 UTC, dgutoryan commented on src/app/posts-module/post/post.component.ts
> +      this.postsService.getPostDetails(id).subscribe((res: Post) => {
It's not the best practice to use subscribe inside another subscribe

2021-09-13 10:40 UTC, dgutoryan commented on src/app/posts-module/post/post.component.ts
> +  post$: Post;
Remove `$` if it's not observable or use observable here instead

2021-09-13 10:40 UTC, dgutoryan commented on src/app/posts-module/post/post.component.ts
> +    this.activatedRoute.params.subscribe((params: Params) => {
I think you don't need t subscribe on params because it isn't changed by time

2021-09-13 10:40 UTC, dgutoryan commented on src/app/posts-module/post/post.component.ts
> +      const id = +params.id;
Let's use `Number(id)` instead

2021-09-13 10:40 UTC, dgutoryan commented on src/app/posts-module/post/post.component.ts
> +      if (isNaN(id)) return;
And nothing happens then?

2021-09-13 10:40 UTC, dgutoryan commented on src/app/posts-module/posts-module.module.ts
> +		RouterModule,
Your `AppRoutingModule` already exports `RouterModule`. So, you don't need to import it

2021-09-13 10:40 UTC, dgutoryan commented on src/app/posts-module/posts/posts.component.html
> +          <a routerLink="/posts/id" class="btn btn-primary" (click)="onSelect(post.id)">Details</a>
Let's use property binding to navigate to post details instead of method

2021-09-13 10:40 UTC, dgutoryan commented on src/app/posts-module/posts/posts.component.ts
> +    this.router.navigate(['posts', id]).then();
You don't need `then` here

2021-09-13 14:05 UTC, dgutoryan commented
`added GET request by id` is too abstract title. Will be better something like `Post details`

2021-09-13 14:16 UTC, dgutoryan requested changes

2021-09-13 14:16 UTC, dgutoryan commented on src/app/posts-module/post/post.component.ts
> +    if (isNaN(id)) this.router.navigate(['/posts']);
Please, use `{}` for condition even if it's small

2021-09-13 14:16 UTC, dgutoryan commented on src/app/posts-module/post/post.component.ts
> +    else this.postsService.getPostDetails(id).subscribe((res: Post) => {
You don't need `else` here, because this code won't execute after navigate

2021-09-14 07:17 UTC, dgutoryan requested changes

2021-09-14 07:17 UTC, dgutoryan commented on src/app/posts-module/post/post.component.html
> +<div *ngIf="post$ | async as asyncPost">
Let's call it just `post` instead `asyncPost`

2021-09-14 07:17 UTC, dgutoryan commented on src/app/app.component.html
> +      <h1 class="py-5 text-center">POSTS TITLE</h1>
I think this every page should have it own title

2021-09-15 07:45 UTC, dgutoryan requested changes

2021-09-15 07:45 UTC, dgutoryan commented on src/app/posts-module/posts-module.module.ts
> +    AppRoutingModule
We discussed that `AppRoutingModule` should be imported in `AppModule` only

2021-09-15 08:28 UTC, dgutoryan approved these changes

2021-09-15 08:52 UTC, timoshevichaleks commented
Added Post details

2021-09-15 08:52 UTC, merged